services:
  dev-db:
    image: postgres:latest
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ibraheem
      POSTGRES_DB: nest
    networks:
      - freecodecamp
  test-db:
    image: postgres:latest
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ibraheem
      POSTGRES_DB: nest
    networks:
      - freecodecamp
networks:
  freecodecamp:
