# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  run_tests:
    docker:
      - image: cimg/node:18.12.0
      - image: circleci/postgres:13.2
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ibraheem
          POSTGRES_DB: nest
          POSTGRES_PORT: 5435
      -image: circleci/redis:6.0
    steps:
      - checkout
      - setup_remote_docker
      
      - run:
          name: install npm dependencies
          command: | 
            npm install
      - run: 
          name: Run run_tests
          command: |
            npm run test:e2e
      - run:
          name: remove database
          command: |
            docker rm -f postgres
      - store_test_results:
          path: test-results
workflows:
  run-tests:
    jobs:
      - run_tests
